### ISSUE TITLE
Backup and History

### ISSUE THREAD

**Issue by ramsesndame237** [ApprentiPro/Blancastory#10]
### Description
The backup and history feature automatically saves the project to prevent data loss and tracks project modification history to keep track of changes.

#### Tasks:
- [ ] Automatically save project
- [ ] Track project modification history

- [ ] Add option to save project to cloud storage service.
- [ ] Add option to track modification history for individual characters, locations, scenes, and plots.
