### ISSUE TITLE
Note Management

### ISSUE THREAD

**Issue by ramsesndame237** [ApprentiPro/Blancastory#6]
### Description
The note management feature allows users to create and modify notes with various attributes such as title, description, and date. Users can add references to notes to provide additional information, and group notes into categories to organize them better.

#### Tasks:
- [ ] Create and modify notes
- [ ] Add references to notes
- [ ] Group notes into categories
- [ ] Add option to create predefined note templates.
- [ ] Add option to link notes to specific characters, locations, scenes, or plots.
- [ ] Add option to track note evolution over time.
