### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by ramsesndame237** [ApprentiPro/Blancastory#9]
### Description
The customization feature allows users to customize the interface appearance according to their preferences, customize export templates according to their needs, and customize custom attributes for characters, locations, and objects according to their needs.

#### Tasks:
- [ ] Customize interface appearance
- [ ] Customize export templates
- [ ] Customize custom attributes for characters, locations, and objects
- [ ] Add option to customize import templates.
- [ ] Add option to customize task templates.
